description: >
   ASPEED AST2700 DCSCM Inventory

events:
    - name: Add PowerState
      description: >
          Create a DBus for power-status-sync.sh to poll SGPIOS value and update to DBus.
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/host0:
                 xyz.openbmc_project.State.Host:
                    PostComplete:
                        value: true
                        type: boolean
                /system/chassis/host0:
                 xyz.openbmc_project.State.Host:
                    PowerButton:
                        value: true
                        type: boolean
                /system/chassis/host0:
                 xyz.openbmc_project.State.Host:
                    PowerOk:
                        value: true
                        type: boolean