/xyz/openbmc_project/control/host{}/power_cap:
    - Interface: xyz.openbmc_project.Control.Power.Cap
      Properties:
          PowerCap:
              Default: 0
          PowerCapEnable:
               Default: 'false'
